name: deploy
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.13.0]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          export PATH=$HOME/.yarn/bin:$PATH

      - name: Install dependencies and build packages
        run: yarn run init

      - name: Publish packages
        env:
          npm_auth_token: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=\$npm_auth_token" >> .npmrc
          yarn run publish-lerna-cutoff